spring.application.name=PPE-Detect-User

# In-memory H2 Database configuration
spring.datasource.url=jdbc:h2:mem:ppedb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Cloudinary properties
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=

# JWT Configuration
jwt.secretkey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000

# App Configuration
app.frontend-redirect-url=http://localhost:5173/login-success

# OAuth2 Client Settings (dummy to satisfy Bean creation)
spring.security.oauth2.client.registration.google.client-id=dummy-client-id
spring.security.oauth2.client.registration.google.client-secret=dummy-client-secret
spring.security.oauth2.client.registration.google.scope=email,profile
